.github/.jira_sync_config.yaml

chore: add jira sync

---

craft_platforms/_distro.py

style: fix ruff issue

---

docs/index.rst
docs/reference/changelog.rst
docs/reference/index.rst

This adds changelog entries for the two existing releases, plus an entry for the upcoming 0.2 release.
-----

docs: add changelog

---

.pre-commit-config.yaml
craft_platforms/_architectures.py
craft_platforms/_platforms.py
pyproject.toml
tests/integration/test_setuptools.py
tests/integration/test_version.py
tox.ini

chore: switch to ruff

---

craft_platforms/__init__.py
craft_platforms/_buildinfo.py
craft_platforms/_errors.py
craft_platforms/_platforms.py
craft_platforms/rock/_build.py
tests/unit/test_errors.py
tests/unit/test_platforms.py

feat: build-for all in generic build planner

---

docs/reference/changelog.rst

docs(changelog): add 0.3.0 to changelog

---

.readthedocs.yaml

fix(docs): make readthedocs build correctly

---

docs/reference/changelog.rst

docs: changelog entries for 0.3.1

---

pyproject.toml

build(deps): update canonical-sphinx

---

Makefile

build(make): s/autoformat/format/

---

.github/workflows/qa.yaml

Since we support it, we should test on it.
-----

ci: test on Python 3.8

---

.readthedocs.yaml
Makefile
craft_platforms/_distro.py
craft_platforms/test/__init__.py
craft_platforms/test/strategies.py
docs/conf.py
docs/reference/changelog.rst
docs/reference/index.rst
docs/reference/testing/index.rst
docs/reference/testing/strategies.rst
pyproject.toml
tests/unit/charm/test_build.py
tests/unit/test/test_strategies.py
tests/unit/test_architectures.py
tests/unit/test_distro.py
tests/unit/test_platforms.py
uv.lock

-----
This adds a module full of hypothesis strategies to help consumers of craft-platforms when testing their code. The strategies generate many valid, but unusual, values. These values are not necessarily valid for each application.
Also adds fuzzers that use these hypothesis strategies.

feat(test): add hypothesis strategies to help with testing

---

uv.lock

chore(autogen): bump jinja2

---

.pre-commit-config.yaml
craft_platforms/snap/_build.py

update ruff pre-commit

---

.github/PULL_REQUEST_TEMPLATE.md
.github/release-drafter.yml
.github/workflows/check-renovate.yaml
.github/workflows/security-scan.yaml
.readthedocs.yaml
Makefile
common.mk
docs/_static/css/custom.css
pyproject.toml
tests/integration/valid-projects/charmcraft-multi.yaml
tests/integration/valid-projects/rockcraft-basic.yaml
uv.lock

-----
This also has the side-effect of getting pyright from snap.

Pull some newer bits from starbase

---

docs/reference/changelog.rst

docs: fix changelog bug fixes markup

---

craft_platforms/_platforms.py
craft_platforms/_utils.py
craft_platforms/charm/_build.py
craft_platforms/test/strategies.py
docs/reference/changelog.rst
tests/integration/valid-projects/charmcraft-multi.yaml
tests/integration/valid-projects/rockcraft-complex.yaml
tests/integration/valid-projects/snapcraft-4.yaml
tests/unit/charm/test_build.py
tests/unit/rock/test_build.py
tests/unit/snap/test_build.py
tests/unit/test/test_strategies.py
tests/unit/test_platforms.py

---
Allow scalar `build-on` and `build-for` values in Platforms.
Fixes #80
(CRAFT-3778)

feat: parse scalar build-ons and build-fors

---

.github/workflows/experimental.yaml
Makefile

ci(experimental): type check with ty

---

pyproject.toml
uv.lock

Inspired by https://github.com/canonical/rockcraft/pull/895
---

test: randomize the order of tests

---

pyproject.toml

chore: update classifiers
